SchoolMS/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SchoolMS.Models
{
    [Table("Staff")]
    public class Staff
    {
        [Key]
        public int StaffID { get; set; }
        [Display(Name ="Designation Title")]
        public int DesignationID { get; set; }
        public int UserID { get; set; }
        [Display(Name = "Select Gender")]
        public int GenderID { get; set; }
        [Required]
        public string Name { get; set; }
        [Display(Name = "Contact No")]
        [Required]
        public string ContactNo { get; set; }
        [Display(Name = "Basic Salary")]
        [Required]
        [DataType(DataType.Currency)]
        public int BasicSalary { get; set; }
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }
        [Required]
        public string Qualification { get; set; }
        [Display(Name = "Picture ")]
        public string Photo { get; set; }
        public string Description { get; set; }
        [Display(Name = "Status")]
        public bool IsActive { get; set; }
   
        [Display(Name = "Home Phone")]
        public string HomePhone { get; set; }
        [Display(Name = "Do you have any disability?")]
        public bool Doyouhaveanydisability { get; set; }
        [Display(Name = "If yes then give us details")]
        public string Ifdisabilityyesthengiveusdetails { get; set; }
        [Display(Name = "Are you taking any medication?")]
        public bool Areyoutakinganymedication { get; set; }
        [Display(Name ="If yes then give us details")]
        public string Ifmedicationyesthengiveusdetail { get; set; }
        [Display(Name = "Any Police record you have?")]
        public bool AnyCriminaloffenceagain { get; set; }
        [Display(Name = "If Yes then give us details")]
        public string Ifcriminaloffenceyesgiveusdetails { get; set; }
        [DataType(DataType.Date)]
        [Required]
        public DateTime RegistrationDate { get; set; }
        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }
        public User Users { get; set; }
        public Designation Designations { get; set; }
        public Gendertbl Gendertbls { get; set; }

    }
}

SchoolMS/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolMS.Models;

namespace SchoolMS.Controllers
{
    public class StaffsController : Controller
    {
        private ApplicationDbContext db;
        public StaffsController()
        {
            db = new ApplicationDbContext();
        }

        // GET: Staffs
        public ActionResult Index()
        {
            var staffs = db.Staffs.Include(s => s.Designations).Include(s => s.Gendertbls).Include(s => s.Users);
            return View(staffs.ToList());
        }

        // GET: Staffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var staff = db.Staffs.Include(s => s.Designations).Include(s => s.Gendertbls).Include(s => s.Users).SingleOrDefault(u=>u.StaffID==id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            ViewBag.DesignationID = new SelectList(db.Designations, "DesignationID", "Name");
            ViewBag.GenderID = new SelectList(db.Gendertbls, "GenderID", "Name");
            ViewBag.UserID = new SelectList(db.Users, "UserID", "FullName");
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Staff staff)
        {
            staff.UserID = 1;

            if (ModelState.IsValid)
            {
                db.Staffs.Add(staff);
                db.SaveChanges();
                if (staff.PhotoFile != null)
                {
                    var folder = "/Content/StaffPhoto";
                    var file = string.Format("{0}.png", staff.StaffID);
                    var response = UploadFile.UploadPhoto(staff.PhotoFile, folder, file);
                    if (response)
                    {
                        var pic = string.Format("{0}/{1}", folder, file);
                        staff.Photo = pic;
                        db.Entry(staff).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }

            ViewBag.DesignationID = new SelectList(db.Designations, "DesignationID", "Name", staff.DesignationID);
            ViewBag.GenderID = new SelectList(db.Gendertbls, "GenderID", "Name", staff.GenderID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "FullName", staff.UserID);
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var staff = db.Staffs.Include(s => s.Designations).Include(s => s.Gendertbls).Include(s => s.Users).SingleOrDefault(u => u.StaffID == id);

            if (staff == null)
            {
                return HttpNotFound();
            }
            ViewBag.DesignationID = new SelectList(db.Designations, "DesignationID", "Name", staff.DesignationID);
            ViewBag.GenderID = new SelectList(db.Gendertbls, "GenderID", "Name", staff.GenderID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "FullName", staff.UserID);
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Staff staff)
        {
            staff.UserID = 1;
            if (ModelState.IsValid)
            {
                if (staff.PhotoFile != null)
                {
                    var folder = "/Content/StaffPhoto";
                    var file = string.Format("{0}.png", staff.StaffID);
                    var response = UploadFile.UploadPhoto(staff.PhotoFile, folder, file);
                    if (response)
                    {
                        var pic = string.Format("{0}/{1}", folder, file);
                        staff.Photo = pic;
                    }
                }
                else
                {
                    staff.Photo = "/Content/StaffPhoto/" + staff.StaffID + ".png";
                }
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DesignationID = new SelectList(db.Designations, "DesignationID", "Name", staff.DesignationID);
            ViewBag.GenderID = new SelectList(db.Gendertbls, "GenderID", "Name", staff.GenderID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "FullName", staff.UserID);
            return View(staff);
            
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var staff = db.Staffs.Include(s => s.Designations).Include(s => s.Gendertbls).Include(s => s.Users).SingleOrDefault(u => u.StaffID == id);

            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.Staffs.Find(id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolMS/Views/Staffs/Create.cshtml
@model SchoolMS.Models.Staff

@{
    ViewBag.Title = "Create";
   
}

<div class="card mb-4 shadow">
    <div class="card-header">
        Staff Information
    </div>
    <div class="card-body">
       @using (Html.BeginForm("Create", "Staffs", FormMethod.Post, new { enctype = "multipart/form-data" }))
       {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DesignationID, "Select Designation", htmlAttributes: new { @class = "control-label " })
                            @Html.DropDownList("DesignationID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.DesignationID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.GenderID, "Select Gender", htmlAttributes: new { @class = "control-label " })
                            @Html.DropDownList("GenderID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.GenderID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Qualification, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.Qualification, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Qualification, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label " })
                            @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.HomePhone, htmlAttributes: new { @class = "control-label " })
                            @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label " })
                            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.BasicSalary, htmlAttributes: new { @class = "control-label " })
                            @Html.EditorFor(model => model.BasicSalary, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BasicSalary, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label " })
                            @*@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.TextAreaFor(model => Model.Description, 3, 0, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <span class="btn btn-default">
                                @Html.TextBoxFor(model => model.PhotoFile, new { type = "file" })
                                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })

                            </span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label " })
                            @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label" })
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <div class="form-group"id="chk1">
                                @Html.LabelFor(model => model.Doyouhaveanydisability, htmlAttributes: new { @class = "control-label " })
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Doyouhaveanydisability)
                                    @Html.ValidationMessageFor(model => model.Doyouhaveanydisability, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-11">
                            <div class="form-group"chk_id="area1">
                                @Html.LabelFor(model => model.Ifdisabilityyesthengiveusdetails, htmlAttributes: new { @class = "control-label" })
                                @*@Html.EditorFor(model => model.Ifdisabilityyesthengiveusdetails, new { htmlAttributes = new { @class = "form-control" } })*@
                                @Html.TextAreaFor(model => Model.Ifdisabilityyesthengiveusdetails, 3, 0, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Ifdisabilityyesthengiveusdetails, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <div class="form-group " id="chk2">
                                @Html.LabelFor(model => model.Areyoutakinganymedication, htmlAttributes: new { @class = "control-label" })
                                <div class="checkbox">
                                    @Html.EditorFor(model => model.Areyoutakinganymedication)
                                    @Html.ValidationMessageFor(model => model.Areyoutakinganymedication, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-11">
                            <div class="form-group" chk_id="area2">
                                @Html.LabelFor(model => model.Ifmedicationyesthengiveusdetail, htmlAttributes: new { @class = "control-label " })
                                @*@Html.EditorFor(model => model.Ifmedicationyesthengiveusdetail, new { htmlAttributes = new { @class = "form-control" } })*@
                                @Html.TextAreaFor(model => Model.Ifmedicationyesthengiveusdetail, 3, 0, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Ifmedicationyesthengiveusdetail, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <div class="form-group">
                                @Html.LabelFor(model => model.AnyCriminaloffenceagain, htmlAttributes: new { @class = "control-label" })
                                <div class="checkbox" id="chk3">
                                    @Html.EditorFor(model => model.AnyCriminaloffenceagain)
                                    @Html.ValidationMessageFor(model => model.AnyCriminaloffenceagain, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-11">
                            <div class="form-group" chk_id="area3">
                                @Html.LabelFor(model => model.Ifcriminaloffenceyesgiveusdetails, htmlAttributes: new { @class = "control-label" })
                                @*@Html.EditorFor(model => model.Ifcriminaloffenceyesgiveusdetails, new { htmlAttributes = new { @class = "form-control" } })*@
                                @Html.TextAreaFor(model => Model.Ifcriminaloffenceyesgiveusdetails, 3, 0, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Ifcriminaloffenceyesgiveusdetails, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>


                    <div class="card-footer">
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-success" />
                                @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
                            </div>
                        </div>
                    </div>
                </div>
        }
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script >
    $(document).ready(function () {
        $("#chk1").change(function () {
            $("#area1").toggle();
        });
    });
</script>

SchoolMS/Views/Staffs/Delete.cshtml
@model SchoolMS.Models.Staff

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Staff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Designations.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designations.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gendertbls.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gendertbls.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BasicSalary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BasicSalary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doyouhaveanydisability)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doyouhaveanydisability)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ifdisabilityyesthengiveusdetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ifdisabilityyesthengiveusdetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Areyoutakinganymedication)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Areyoutakinganymedication)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ifmedicationyesthengiveusdetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ifmedicationyesthengiveusdetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnyCriminaloffenceagain)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnyCriminaloffenceagain)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ifcriminaloffenceyesgiveusdetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ifcriminaloffenceyesgiveusdetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolMS/Views/Staffs/Details.cshtml
@model SchoolMS.Models.Staff

@{
    ViewBag.Title = "Details";
}


<div class="card mb-4 shadow">
    <div class="card-header">
        Staff  Details
    </div>
    <div class="card-body">
        <dl class="dl-horizontal">
            <dd>
                @if (!String.IsNullOrEmpty(Model.Photo))
                {
                    <img src="@Url.Content(Model.Photo)" alt="Image" style="width:160px;height:220px;max-width:100%;height:auto;" />
                }
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Designations.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Designations.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Gendertbls.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gendertbls.Name)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.ContactNo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactNo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.BasicSalary)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.BasicSalary)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmailAddress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Qualification)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Qualification)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HomePhone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HomePhone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Doyouhaveanydisability)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Doyouhaveanydisability)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ifdisabilityyesthengiveusdetails)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ifdisabilityyesthengiveusdetails)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Areyoutakinganymedication)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Areyoutakinganymedication)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ifmedicationyesthengiveusdetail)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ifmedicationyesthengiveusdetail)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AnyCriminaloffenceagain)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AnyCriminaloffenceagain)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ifcriminaloffenceyesgiveusdetails)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ifcriminaloffenceyesgiveusdetails)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RegistrationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RegistrationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Users.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Users.FullName)
            </dd>

        </dl>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Edit", "Edit", new { id = Model.StaffID }, new { @class = "btn btn-success" }) |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>