SchoolMS/Models/SubmessionFee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SchoolMS.Models
{
    [Table("SubmessionFee")]
    public class SubmessionFee
    {
        [Key]
        public int SubmissionFeeID { get; set; }
        [Display(Name ="Class Title")]
        [Required]
        public int StudentPromoteID { get; set; }
        public int UserID { get; set; }
        [Display(Name="Amount / Fee's")]
        [Required]
        public int Amount { get; set; }
        [Required]
        [Display(Name ="Date")]
        [DataType(DataType.Date)]
        public DateTime SubmissionDate { get; set; }
        [Required]
        [Display(Name = "Select Fee Month")]
        public int MonthID { get; set; }
        public string Description { get; set; }
        [Display(Name = "Status")]


        public User Users { get; set; }
        public StudentPromote StudentPromotes { get; set; }
        public MonthsModel MonthsModels { get; set; }
    }
}

SchoolMS/Controllers/SubmessionFeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SchoolMS.Models;
using SchoolMS.ModelsViews;

namespace SchoolMS.Controllers
{
    public class SubmessionFeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: SubmessionFees
        public ActionResult Index()
        {
           
            var submessionFees = db.SubmessionFees.Include(u=>u.StudentPromotes.Students)
                .Include(u=>u.StudentPromotes.Annuals).Include(s => s.MonthsModels).Include(s => s.Users).ToList();
 

            return View(submessionFees);
        }

        // GET: SubmessionFees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
          
            var model = db.SubmessionFees.Include(u=>u.StudentPromotes.Annuals).Include(u=>u.Users).Include(u=>u.MonthsModels)
                .Include(u=>u.StudentPromotes.Students)
                .Single(u => u.SubmissionFeeID == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // GET: SubmessionFees/Create
        public ActionResult Create()
        {
            
            var model = new ForSubmissionFeeCreateViewModel()
            {
                studentpromote = db.StudentPromotes.Include(u => u.Annuals).Include(u => u.Students).ToList().Where(u => u.IsActive != false),
            submessionFee = new SubmessionFee(),
                monthmodel=db.MonthsModels.ToList()
               
            };
         
            return View(model);
        }

        // POST: SubmessionFees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SubmessionFee submessionFee)
        {
            if (ModelState.IsValid)
            {
                submessionFee.UserID=1;
                db.SubmessionFees.Add(submessionFee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var model = new ForSubmissionFeeCreateViewModel()
            {
                studentpromote = db.StudentPromotes.Include(u => u.Annuals).Include(u => u.Students).ToList().Where(u => u.IsActive != false),
                submessionFee =submessionFee,
                monthmodel = db.MonthsModels.ToList()

            };

            
            return View(model);
        }

        // GET: SubmessionFees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = new ForSubmissionFeeCreateViewModel()
            {
                studentpromote = db.StudentPromotes.Include(u => u.Annuals).Include(u => u.Students).ToList().Where(u => u.IsActive != false),
                submessionFee =db.SubmessionFees.Include(u=>u.StudentPromotes).Single(u=>u.SubmissionFeeID==id)   ,
                monthmodel = db.MonthsModels.ToList()

            };
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
         
  
        }

        // POST: SubmessionFees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SubmessionFee submessionFee)
        {
            submessionFee.UserID = 1; 
            if (ModelState.IsValid)
            {
                db.Entry(submessionFee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var model = new ForSubmissionFeeCreateViewModel()
            {
                studentpromote = db.StudentPromotes.Include(u => u.Annuals).Include(u => u.Students).ToList().Where(u => u.IsActive != false),
                submessionFee = submessionFee,
                monthmodel = db.MonthsModels.ToList()

            };
            return View(model);
        }

        // GET: SubmessionFees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = db.SubmessionFees.Include(u => u.StudentPromotes.Annuals).Include(u => u.Users).Include(u => u.MonthsModels)
              .Include(u => u.StudentPromotes.Students)
              .Single(u => u.SubmissionFeeID == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: SubmessionFees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SubmessionFee submessionFee = db.SubmessionFees.Find(id);
            db.SubmessionFees.Remove(submessionFee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolMS/Views/SubmessionFees/Create.cshtml
@model SchoolMS.ModelsViews.ForSubmissionFeeCreateViewModel

@{
    ViewBag.Title = "Create";
}
<div class="card mb-4 shadow">
    <div class="card-header">
        Search Student By
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Student Name
                        </th>
                        <th>
                            Father
                        </th>
                        <th>
                            Class
                        </th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.studentpromote)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Students.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Students.FatherName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Annuals.Title)
                            </td>
                            <td >
                                @*@Html.b("Load Record", "", new { id = item.StudentPromoteID }, new { @class = "btn btn-primary" })*@
                                <button class="btn btn-primary js-Delete" data-promote-id=@item.StudentPromoteID data-student-id=@item.StudentID> Load Record</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>


<div id="MainContID"  >
@using (Html.BeginForm("Edit","SubmessionFees"))
{
    @Html.AntiForgeryToken()
    <div class="card mb-4 shadow">
        <div class="card-header">
            Adding New Fee
        </div>
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <h1 style="text-align:center;color:seagreen" id="studentID" ></h1>
               
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.studentpromote, "Class", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownListFor(m=>m.submessionFee.StudentPromoteID,new SelectList(Model.studentpromote,"",""),"Select Class",  new { @class = "form-control", @id = "promoteId" })
                    @Html.ValidationMessageFor(model => model.submessionFee.StudentPromoteID, "", new { @class = "text-danger" })
                </div>
            </div>

    

              <div class="form-group">
                    @Html.LabelFor(model => model.submessionFee.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.submessionFee.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.submessionFee.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
            <div class="form-group">
                @Html.LabelFor(model => model.submessionFee.MonthID, "MonthID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownListFor(model=>model.submessionFee.MonthID,new SelectList(Model.monthmodel,"MonthID","Name") , new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.submessionFee.MonthID, "", new { @class = "text-danger" })
                </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.submessionFee.SubmissionDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.submessionFee.SubmissionDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.submessionFee.SubmissionDate, "", new { @class = "text-danger" })
                    </div>
                </div>

              
                <div class="form-group">
                    @Html.LabelFor(model => model.submessionFee.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.submessionFee.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.submessionFee.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success"/>
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}
    </div>
<script src="~/Scripts/jquery-1.10.2.js"></script>

<script>
    $(document).ready(function () {
        $("#dataTable").on("click", ".js-Delete", function () {
            $('#MainContID').hide(1);
           
            var button = $(this);
            $('#promoteId').html('');
            var className = $(this).closest("tr").find('td:eq(2)').text();
            $('#promoteId').append("<option value=" + button.attr('data-promote-id') + ">" + className + "</option>")
            $('#studentID').text($(this).closest("tr").find('td:eq(0)').text()+'( '+button.attr("data-student-id")+" )");
            $('#MainContID').show(2000);
        });
    });
</script>

SchoolMS/Views/SubmessionFees/Delete.cshtml
@model SchoolMS.Models.SubmessionFee

@{
    ViewBag.Title = "Delete";
}
<div class="card mb-4 shadow">
    <div class="card-header">
        Are you sure you want to delete this?
    </div>
    <div class="card-body">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StudentPromotes.Students.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StudentPromotes.Students.Name) ( @Html.DisplayFor(model => model.StudentPromotes.Students.StudentID) )
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.StudentPromotes.Annuals.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StudentPromotes.Annuals.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.MonthsModels.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MonthsModels.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Amount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Amount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SubmissionDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubmissionDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Users.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Users.FullName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        }
    </div>
</div>


SchoolMS/Views/SubmessionFees/Details.cshtml
@model SchoolMS.Models.SubmessionFee

@{
    ViewBag.Title = "Details";
}
<div class="card mb-4 shadow">
    <div class="card-header">
        Submission Fee Details
    </div>
    <div class="card-body">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.StudentPromotes.Students.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StudentPromotes.Students.Name) ( @Html.DisplayFor(model => model.StudentPromotes.Students.StudentID) )
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.StudentPromotes.Annuals.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StudentPromotes.Annuals.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.MonthsModels.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MonthsModels.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Amount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Amount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SubmissionDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SubmissionDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Users.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Users.FullName)
            </dd>

        </dl>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Edit", "Edit", new { id = Model.SubmissionFeeID }, new { @class = "btn btn-success" }) |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
</div>

SchoolMS/Views/SubmessionFees/Edit.cshtml
@model SchoolMS.ModelsViews.ForSubmissionFeeCreateViewModel

@{
    ViewBag.Title = "Edit";
}
<div class="card mb-4 shadow">
    <div class="card-header">
        Search Student By
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Student Name
                        </th>
                        <th>
                            Father
                        </th>
                        <th>
                            Class
                        </th>


                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.studentpromote)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Students.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Students.FatherName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Annuals.Title)
                            </td>
                            <td>
                                @*@Html.b("Load Record", "", new { id = item.StudentPromoteID }, new { @class = "btn btn-primary" })*@
                                <button class="btn btn-primary js-Delete" data-promote-id=@item.StudentPromoteID data-student-id=@item.StudentID> Load Record</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card mb-4 shadow">
        <div class="card-header">
            Editing Fee's
        </div>
        <div class="card-body">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.submessionFee.SubmissionFeeID)

            <div class="form-group">
                <h1 style="text-align:center;color:seagreen" id="studentID"></h1>

            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.studentpromote, "Class", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownListFor(m => m.submessionFee.StudentPromoteID, new SelectList(Model.studentpromote, "", ""), "Select Class", new { @class = "form-control", @id = "promoteId" })
                    @Html.ValidationMessageFor(model => model.submessionFee.StudentPromoteID, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.submessionFee.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.submessionFee.Amount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.submessionFee.Amount, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.submessionFee.MonthID, "MonthID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.DropDownListFor(model => model.submessionFee.MonthID, new SelectList(Model.monthmodel, "MonthID", "Name"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.submessionFee.MonthID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.submessionFee.SubmissionDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.submessionFee.SubmissionDate, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.submessionFee.SubmissionDate, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.submessionFee.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.submessionFee.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.submessionFee.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts/jquery-1.10.2.js"></script>

<script>
    $(document).ready(function () {
        $("#dataTable").on("click", ".js-Delete", function () {   
            var button = $(this);
            $('#promoteId').html('');
            var className = $(this).closest("tr").find('td:eq(2)').text();
            $('#promoteId').append("<option value=" + button.attr('data-promote-id') + ">" + className + "</option>")
            $('#studentID').text($(this).closest("tr").find('td:eq(0)').text()+'( '+button.attr("data-student-id")+" )");
        });
        var model=@Html.Raw(Json.Encode(Model.submessionFee.StudentPromoteID));
        $('#promoteId').html('');
        $('#dataTable tr').each(function () {
            $(this).find('td:nth-child(4)').each(function () {
                var v = $(this).find(".js-Delete");
                if (v.attr('data-promote-id') ==model)
                {
                    $('#studentID').text(v.closest("tr").find('td:eq(0)').text()+'( '+v.attr("data-student-id")+" )");
                    $('#promoteId').append("<option value=" +v.attr('data-promote-id')+ ">" +v.closest("tr").find('td:eq(2)').text()+ "</option>")
                }
            });
        });
       

    });
</script>


SchoolMS/Views/SubmessionFees/Index.cshtml
@model IEnumerable<SchoolMS.Models.SubmessionFee>

@{
    ViewBag.Title = "Index";
}
<p>
    @Html.ActionLink("Add New Fee", "Create", null, new { @class = "btn btn-success" })
</p>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Class List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Student Name
                        </th>
                        <th>
                            Class Title
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SubmissionDate)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Amount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.MonthsModels.Name)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Users.FullName)
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.StudentPromotes.Students.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.StudentPromotes.Annuals.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SubmissionDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Amount)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MonthsModels.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Users.FullName)
                            </td>
                   

                                <td class="btn-group">
                                    @Html.ActionLink("Edit", "Edit", new { id = item.SubmissionFeeID }, new { @class = "btn btn-primary" })
                                    @Html.ActionLink("Details", "Details", new { id = item.SubmissionFeeID }, new { @class = "btn btn-info" })
                                    @Html.ActionLink("Delete", "Delete", new { id = item.SubmissionFeeID }, new { @class = "btn btn-danger" })
                                </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>